import "./style.css";
import "./globals.css";
import { cookies } from "next/headers";
import NextLoader from "@/components/NextTopLoader";
import { Geist, Geist_Mono } from "next/font/google";
import { SnackbarProvider } from "@/components/Snackbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Personal Data",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const theme = cookieStore.get("theme")?.value || "light";
  return (
    <html lang="en" data-theme={theme}>
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        <SnackbarProvider>
          <NextLoader />
          {children}
        </SnackbarProvider>
      </body>
    </html>
  );
}
